- name: No vlan and interface vlan
  hosts: all
  connection: network_cli
  gather_facts: no
  tasks:
    - name: No vlan 132
      cisco.ios.ios_config:  # Thêm cisco.ios. vào trước
        lines:
          - no vlan 132

    - name: No interface Vlan 132
      cisco.ios.ios_config:  # Thêm cisco.ios. vào trước
        lines:
          - no interface vlan 132
